# Generated by Django 3.2 on 2021-04-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrecipe',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='foodrecipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='foodrecipe',
            name='servings_number',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='kcal_value_100g',
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='food_recipes', to='cookbook.Ingredient'),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='dish_type',
            field=models.CharField(choices=[('BF', 'breakfast'), ('SD', 'salad'), ('AP', 'appetizer'), ('SP', 'soup'), ('MC', 'main course'), ('DS', 'dessert')], max_length=2),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FoodRecipeIngredient',
        ),
    ]
