# Generated by Django 3.2 on 2021-04-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20210413_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodRecipe',
        ),
    ]
